import { useAuth } from "@/contexts/useAuth";

//Permissao por role
//Usado para controlar visibilidade de botoes e ações

const ROLE_PERMISSIONS: Record<string, string[]> = {
   admin: [
      "manage_farms",
      "manage_breeds",
      "create_farm",
      "edit_farm",
      "delete_farm",
      "activate_farm",
      "deactivate_farm",
      "view_all_farms",
      "register_veterinarian",
      "edit_veterinarian",
      "delete_veterinarian",
      "create_user_any_role",
      "create_user",
      "edit_user",
      "delete_user",
      "activate_user",
      "deactivate_user",
      "reset_user_password",
      "view_global_audit",
      "create_animal",
      "edit_animal",
      "delete_animal",
      "place_ear_tag",
      "remove_ear_tag",
      "delete_ear_tag_history",
      "register_estrus",
      "edit_estrus",
      "register_mating",
      "register_ultrasound_30",
      "register_ultrasound_60",
      "register_final_ultrasound",
      "edit_pregnancy",
      "register_birth",
      "edit_birth",
      "delete_birth",
      "create_calf",
      "register_vaccination",
      "edit_vaccination",
      "upload_vaccination_photo",
      "register_management",
      "move_batch",
      "create_pasture",
      "edit_pasture",
      "delete_pasture",
      "register_mortality",
      "edit_mortality",
      "upload_mortality_photo",
      "view_reports",
      "export_pdf",
      "export_csv",
      "create_buyer",
      "edit_buyer",
      "delete_buyer",
      "view_buyers",
      "register_weighing",
      "edit_weighing",
      "delete_weighing",
      "view_weighing",
   ],
   owner: [
      "create_user",
      "edit_user",
      "delete_user",
      "activate_user",
      "deactivate_user",
      "reset_user_password",
      "create_farmmanager_user",
      "create_veterinarian_user",
      "create_animal",
      "edit_animal",
      "delete_animal",
      "place_ear_tag",
      "remove_ear_tag",
      "delete_ear_tag_history",
      "register_estrus",
      "edit_estrus",
      "register_mating",
      "register_ultrasound_30",
      "register_ultrasound_60",
      "register_final_ultrasound",
      "edit_pregnancy",
      "register_birth",
      "edit_birth",
      "delete_birth",
      "create_calf",
      "register_vaccination",
      "edit_vaccination",
      "upload_vaccination_photo",
      "register_management",
      "move_batch",
      "create_pasture",
      "edit_pasture",
      "delete_pasture",
      "register_mortality",
      "edit_mortality",
      "upload_mortality_photo",
      "view_reports",
      "export_pdf",
      "export_csv",
      "create_buyer",
      "edit_buyer",
      "delete_buyer",
      "view_buyers",
      "register_weighing",
      "edit_weighing",
      "delete_weighing",
      "view_weighing",
   ],
   farmmanager: [
      "create_animal",
      "edit_animal",
      "delete_animal",
      "place_ear_tag",
      "remove_ear_tag",
      "create_pasture",
      "edit_pasture",
      "delete_pasture",
      "register_estrus",
      "edit_estrus",
      "register_mating",
      "register_ultrasound_30",
      "edit_pregnancy",
      "register_birth",
      "edit_birth",
      "delete_birth",
      "register_vaccination",
      "edit_vaccination",
      "register_management",
      "move_batch",
      "register_mortality",
      "edit_mortality",
      "activate_user",
      "deactivate_user",
      "view_reports",
      "export_pdf",
      "export_csv",
      "register_weighing",
      "edit_weighing",
      "delete_weighing",
      "view_weighing",
   ],
   veterinarian: [
      // Veterinário SÓ visualiza animais — não cria, edita ou deleta
      "register_vaccination",
      "edit_vaccination",
      "register_ultrasound_30",
      "register_birth",
      "edit_birth",
      "register_mortality",
      "register_estrus",
      "register_weighing",
      "view_weighing",
   ],
};
//hook principal - retorna função can() para checar permissoes
export function usePermission() {
   const { user } = useAuth();

   //can("create_animal") -> true/false
   function can(permission: string): boolean {
      if (!user) return false;
      const perms = ROLE_PERMISSIONS[user.role] ?? [];
      return perms.includes(permission);
   }
   return { can, hasPermission: can };
}
